version: 0.0.1
server:
  rootPath: /api/
  applicationConnectors:
    - type: http
      port: 8088

# Logging settings.
logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout